=== liangzai-cool/learn-drools/src/main/resources/rule-config.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rule-config">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="title"/>
                <xs:element type="xs:string" name="description"/>
                <xs:element name="rule-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rule" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="id"/>
                                        <xs:element type="xs:string" name="group-id"/>
                                        <xs:element type="xs:string" name="title"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="version"/>
                                        <xs:element type="xs:string" name="code"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== liangzai-cool/learn-drools/src/main/resources/rule-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<rule-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="rule-config.xsd">
    <title>title-1</title>
    <description>description-1</description>
    <rule-list>
        <rule>
            <id>id-1</id>
            <group-id>group-id-1</group-id>
            <title>title-1</title>
            <description>description-1</description>
            <version>version-1</version>
            <code>
                <![CDATA[
                    rule "Hello World"
                        when
                            // 规则的条件
                            $m : String( length >= 0 )
                        then
                            // 规则的操作
                            System.out.println( "id-1-Hello, " + $m );
                    end
                ]]>
            </code>
        </rule>

        <rule>
            <id>id-11</id>
            <group-id>group-id-1</group-id>
            <title>title-11</title>
            <description>description-11</description>
            <version>version-1</version>
            <code>
                <![CDATA[
                    rule "1Hello-World"
                        when
                            // 规则的条件
                            $m : String( length >= 0 )
                        then
                            // 规则的操作
                            System.out.println( "id-11-Hello, " + $m );
                    end
                ]]>
            </code>
        </rule>
        <rule>
            <id>id-2</id>
            <group-id>group-id-2</group-id>
            <title>title-2</title>
            <description>description-2</description>
            <version>version-2</version>
            <code>
                <![CDATA[
                    rule "2Hello-World"
                        when
                            // 规则的条件
                            $m : String( length >= 0 )
                        then
                            // 规则的操作
                            System.out.println( "id-2-Hello, " + $m );
                    end
                ]]>
            </code>
        </rule>
    </rule-list>
</rule-config>
